# Naive Bayes

## Import thư viện

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import bộ dữ liệu

In [ ]:
dataset = pd.read_csv('heart.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Chia bộ dữ liệu thành tập train và tập test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[58.  1.  2. ...  2.  2.  3.]
 [52.  1.  0. ...  2.  1.  2.]
 [54.  1.  2. ...  2.  0.  3.]
 ...
 [56.  1.  3. ...  1.  0.  3.]
 [47.  1.  2. ...  2.  0.  2.]
 [58.  1.  1. ...  1.  0.  2.]]


In [ ]:
print(y_train)

[0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0
 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1
 1 1 1 0 0 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0
 0 1 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0
 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1
 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0
 0 0 1 1 0]


In [ ]:
print(X_test)

[[7.00e+01 1.00e+00 0.00e+00 1.45e+02 1.74e+02 0.00e+00 1.00e+00 1.25e+02
  1.00e+00 2.60e+00 0.00e+00 0.00e+00 3.00e+00]
 [6.40e+01 1.00e+00 3.00e+00 1.70e+02 2.27e+02 0.00e+00 0.00e+00 1.55e+02
  0.00e+00 6.00e-01 1.00e+00 0.00e+00 3.00e+00]
 [5.90e+01 1.00e+00 3.00e+00 1.70e+02 2.88e+02 0.00e+00 0.00e+00 1.59e+02
  0.00e+00 2.00e-01 1.00e+00 0.00e+00 3.00e+00]
 [6.00e+01 1.00e+00 0.00e+00 1.25e+02 2.58e+02 0.00e+00 0.00e+00 1.41e+02
  1.00e+00 2.80e+00 1.00e+00 1.00e+00 3.00e+00]
 [6.20e+01 1.00e+00 2.00e+00 1.30e+02 2.31e+02 0.00e+00 1.00e+00 1.46e+02
  0.00e+00 1.80e+00 1.00e+00 3.00e+00 3.00e+00]
 [4.80e+01 1.00e+00 0.00e+00 1.24e+02 2.74e+02 0.00e+00 0.00e+00 1.66e+02
  0.00e+00 5.00e-01 1.00e+00 0.00e+00 3.00e+00]
 [4.00e+01 1.00e+00 0.00e+00 1.10e+02 1.67e+02 0.00e+00 0.00e+00 1.14e+02
  1.00e+00 2.00e+00 1.00e+00 0.00e+00 3.00e+00]
 [6.30e+01 1.00e+00 0.00e+00 1.30e+02 2.54e+02 0.00e+00 0.00e+00 1.47e+02
  0.00e+00 1.40e+00 1.00e+00 1.00e+00 3.00e+00]
 [5.60e+01 0.00e+00 0.00

In [ ]:
print(y_test)

[0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0
 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0
 0 1]


## Scale dữ liệu

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.35256528  0.70243936  0.9870291  ...  0.96222601  1.22723311
   1.12135917]
 [-0.31068598  0.70243936 -0.91982712 ...  0.96222601  0.25993479
  -0.45968761]
 [-0.08960223  0.70243936  0.9870291  ...  0.96222601 -0.70736353
   1.12135917]
 ...
 [ 0.13148153  0.70243936  1.94045721 ... -0.6557392  -0.70736353
   1.12135917]
 [-0.86339537  0.70243936  0.9870291  ...  0.96222601 -0.70736353
  -0.45968761]
 [ 0.35256528  0.70243936  0.03360099 ... -0.6557392  -0.70736353
  -0.45968761]]


In [ ]:
print(X_test)

[[ 1.67906782  0.70243936 -0.91982712  0.77497606 -1.35743293 -0.42695628
   0.89174012 -1.04934923  1.38212026  1.22827842 -2.27370441 -0.70736353
   1.12135917]
 [ 1.01581655  0.70243936  1.94045721  2.22645762 -0.380682   -0.42695628
  -0.9825655   0.238927   -0.72352604 -0.4269261  -0.6557392  -0.70736353
   1.12135917]
 [ 0.46310716  0.70243936  1.94045721  2.22645762  0.74350304 -0.42695628
  -0.9825655   0.41069717 -0.72352604 -0.757967   -0.6557392  -0.70736353
   1.12135917]
 [ 0.57364904  0.70243936 -0.91982712 -0.38620919  0.19062515 -0.42695628
  -0.9825655  -0.36226857  1.38212026  1.39379887 -0.6557392   0.25993479
   1.12135917]
 [ 0.79473279  0.70243936  0.9870291  -0.09591288 -0.30696495 -0.42695628
   0.89174012 -0.14755587 -0.72352604  0.56619661 -0.6557392   2.19453143
   1.12135917]
 [-0.75285349  0.70243936 -0.91982712 -0.44426845  0.48549336 -0.42695628
  -0.9825655   0.71129496 -0.72352604 -0.50968632 -0.6557392  -0.70736353
   1.12135917]
 [-1.63718851  0.70243

## Train model Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Dự đoán kết quả với input bất kì

In [ ]:
print(classifier.predict(sc.transform([[19,1,2,150,200,1,1,160,1,1,1,0,2]])))

[1]


## Dự đoán kết quả trên tập test

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


## Tạo confusion matrix và print accuracy, precison, recall và f1 của model

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print('confusion matrix: \n', cm)
print('accuracy: ', accuracy_score(y_test, y_pred))
print('precision: ', precision_score(y_test, y_pred))
print('recall: ', recall_score(y_test, y_pred))
print('f1_score: ', f1_score(y_test, y_pred))

confusion matrix: 
 [[24  9]
 [ 4 39]]
accuracy:  0.8289473684210527
precision:  0.8125
recall:  0.9069767441860465
f1_score:  0.8571428571428572
